apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: rebalancer
  newName: 743156738557.dkr.ecr.us-east-1.amazonaws.com/rebalancer
  newTag: 4044a09c5db28103076de765b8fded4c9bdfa62b
resources:
- ../../base
