apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: rebalancer
  newName: 743156738557.dkr.ecr.us-east-1.amazonaws.com/rebalancer
  newTag: fb2d2b9b16a202ec684c0f4b9d13fefd2cd0a439
resources:
- ../../base
