apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: rebalancer
  newName: 743156738557.dkr.ecr.us-east-1.amazonaws.com/rebalancer
  newTag: 70f4f9afef7b4eee995413ae6a087123b4a8d32e
resources:
- ../../base
