apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: rebalancer
  newName: 743156738557.dkr.ecr.us-east-1.amazonaws.com/rebalancer
  newTag: 23bd2d8fe78d021fcb7c829df1af0e81b41f8b88
resources:
- ../../base
