apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: rebalancer
  newName: 743156738557.dkr.ecr.us-east-1.amazonaws.com/rebalancer
  newTag: 8c8dfef6b10598b579f65cf6ade443a2eff983eb
resources:
- ../../base
