apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
images:
- name: rebalancer
  newName: 743156738557.dkr.ecr.us-east-1.amazonaws.com/rebalancer
  newTag: f1aa62e2eee0c35666382db5cfc6e6ee9b77d1fe
resources:
- ../../base
