apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
images:
- name: queuebot
  newName: 743156738557.dkr.ecr.us-east-1.amazonaws.com/queuebot
  newTag: f4c44cc5ec8bfaffd289a4d25e68b468491c8417
resources:
- ../../base
