apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
images:
- name: queuebot
  newName: 743156738557.dkr.ecr.us-east-1.amazonaws.com/queuebot
  newTag: b40f926ae8850ad7b7c294c17717649910564a41
resources:
- ../../base
