apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
images:
- name: rebalancer
  newName: 959984261658.dkr.ecr.us-east-2.amazonaws.com/rebalancer
  newTag: e83e340f9ff9a1597601fc4dca2a55d3cbc1644a
resources:
- ../../base
