apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
images:
- name: rebalancer
  newName: 959984261658.dkr.ecr.us-east-2.amazonaws.com/rebalancer
  newTag: 92a11b6d593487f101e525fa48c4b4d0e175f33c
resources:
- ../../base
