# This workflow builds docker image to run rebalance script.

name: Smart Contracts PR Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on PR
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      
      - name: Install DappTools
        run: curl https://dapp.tools/install | sh

      - name: Build and test with dapptools
        run: yarn test

      - name: Check gas snapshot
        run: yarn snap

      - name: Check lint errors
        run: yarn lint

      - name: Check formatting errors
        run: yarn format

      - name: Check if docker image for rebalancer builds
        run: docker build -t alpine-sc:temp .
