apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
images:
- name: rebalancer
  newName: 959984261658.dkr.ecr.us-east-2.amazonaws.com/rebalancer
  newTag: ada845be48f26de69607018920bfed02f1f66327
resources:
- ../../base
