apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
images:
- name: rebalancer
  newName: 959984261658.dkr.ecr.us-east-2.amazonaws.com/rebalancer
  newTag: 07d9d600a949bef9e9ad8054f9d63125e81d5b79
resources:
- ../../base
