apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
images:
- name: rebalancer
  newName: 959984261658.dkr.ecr.us-east-2.amazonaws.com/rebalancer
  newTag: cfc8b51f87ee9346dc0acc6b88d301102cd1c5ba
resources:
- ../../base
